apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: hello-world-viewer
  namespace: default
spec:
  rules:
    - services: ["covid19info.default.svc.cluster.local"]
      path: ["*/covid"]
      methods: ["GET"]