apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-1-0-0-snapshot
  labels:
    app: helloworld
    version: 1-0-0-snapshot
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: helloworld
        version: 1-0-0-snapshot
        env: production
    spec:
      containers:
        - name: helloworld
          image: localhost:5000/helloworld:1.0.0-SNAPSHOT
          #          resources:
          #            limits:
          #              memory: "500Mi"
          #              cpu: "100m"
          imagePullPolicy: Always
          readinessProbe:
            # Readiness probe is used to check if this app is ready to serve traffic.
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
          livenessProbe:
            # Liveness probe is used to check if this app is responding to requests
            # (after it is marked as "ready").
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: COMPONENT
              value: backend
            - name: VERSION
              value: production
            - name: jasypt.encryptor.password
              valueFrom:
                configMapKeyRef:
                  name: helloworld-backend-configmap
                  key: JASYPT_ENCRYPTOR_PASSWORD
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 5
  selector:
    matchLabels:
      app: helloworld