kind: Service
apiVersion: v1
metadata:
  labels:
    app: helloworld-backend-service-canary
  name: helloworld-backend-service-canary
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    role: backend
    app: helloworld
    env: canary
#  sessionAffinity: None
  type: LoadBalancer