kind: Service
apiVersion: v1
metadata:
  labels:
    app: helloworld-backend-service-canary
  namespace: spinnaker
  name: helloworld-backend-service-canary
spec:
  ports:
    - name: 8080-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    role: backend
    app: helloworld
    env: canary
  sessionAffinity: None
  type: NodePort