kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: helloworld
  sessionAffinity: None
  type: LoadBalancer
